language: scala
sudo: false
jdk: openjdk8
scala:
- 2.11.12
- 2.12.10
- 2.13.1
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" test
matrix:
  include:
  - scala: 2.12.10
    dist: xenial
    jdk: openjdk11
  - scala: 2.11.12
    dist: trusty
    env: JDK7_TEST
    script:
    - sbt "java++ 1.7" "++ ${TRAVIS_SCALA_VERSION}!" test
